バックエンドのアーキテクチャを設計
ritscc/Snack pull request #64
Opened 2023-05-27 13:28 UTC by CityBear3

close: #38

2023-05-28 11:48 UTC, CityBear3 commented
@1uf3 @hane0817 
バックエンドのアーキテクチャについて最低限は書いたので、足りないものがある場合は指摘してください。

2023-05-29 00:01 UTC, 1uf3 commented
READMEに記載されていることは、おそらく初めての人では理解ができないと思うので、何かしら例やわかりやすい図を入れたほうがいいかもしれません。

あと、改行を<br>ではなく、空白2つにしてほしいです。

2023-05-29 00:06 UTC, 1uf3 requested changes
READMEに記載されていることは、おそらく初めての人では理解ができないと思うので、何かしら具体例やわかりやすい図を入れたほうがいいかもしれません。

あと、改行を`<br>`ではなく、空白2つにしてほしいです。

とりあえず改行の件で変更お願いします。

2023-05-29 06:05 UTC, 1uf3 commented on backend/README.md
> +https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
URLを書き込んでいるので、２つ目のURLはいらなそう。

2023-05-29 08:49 UTC, hane0817 commented
様々なソフトウェアアーキテクチャがありますが，今回はなぜクリーンアーキテクチャなんですか？

2023-05-31 03:51 UTC, hane0817 approved these changes

2023-05-31 06:02 UTC, 1uf3 commented
> 様々なソフトウェアアーキテクチャがありますが，今回はなぜクリーンアーキテクチャなんですか？

これは教えてもらったんですか？

2023-05-31 08:24 UTC, CityBear3 commented
> > 様々なソフトウェアアーキテクチャがありますが，今回はなぜクリーンアーキテクチャなんですか？
> 
> これは教えてもらったんですか？

解説して、納得してもらいました

2023-05-31 08:25 UTC, CityBear3 commented on backend/README.md
> +https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
下のURLは出典としてです。

2023-05-31 08:56 UTC, 1uf3 commented on backend/README.md
> +https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
だとしたら改行がほしいので空白２つ入れてほしい．
Githubでの表示を見てみてください

2023-05-31 08:59 UTC, 1uf3 commented on backend/README.md
> +https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
```suggestion
![依存関係](https://blog.cleancoder.com/uncle-bob/images/2012-08-13-the-clean-architecture/CleanArchitecture.jpg)  
https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
```

2023-06-01 17:22 UTC, 1uf3 approved these changes
LGTM

2023-06-01 23:16 UTC, merged